# Generated by Django 4.0.4 on 2022-06-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_scriptum_options_alter_magazine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='alias',
        ),
        migrations.AddField(
            model_name='scriptum',
            name='author_pseudonym',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
